# Site settings
title: Sheila Wittman's Professional Blog
header-img: img/home-bg.png
email: szandora789@gmail.com
copyright_name: Szandora
description: > # this means to ignore newlines until "baseurl:"
  An online portfolio
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Szandora
learn_profile: Szandora
email_username: szandora789@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
